// Dynamic Expo config layered on top of app.json.
//
// app.json stays the single source of truth for everything that does NOT
// vary by build. Expo reads it first and hands its `expo` block to the
// function below as `config`; we spread it through untouched and override
// ONLY the one value that has to change per EAS build profile:
//
//   ios.entitlements["aps-environment"]
//
// Why it can't be static:
//   - It can't live in the committed native project — `ios/` is
//     gitignored and regenerated by `expo prebuild` on every EAS build,
//     so any hand-edit to ios/WhatIf/WhatIf.entitlements is wiped.
//   - It can't be a fixed value in app.json — each profile needs a
//     different APNs environment, and hardcoding "production" would break
//     the dev profile's signing/sandbox push:
//
//       development profile → dev-signed → SANDBOX  APNs → "development"
//       preview     profile → ad-hoc     → PRODUCTION APNs → "production"
//       production  profile → store      → PRODUCTION APNs → "production"
//       no profile (local `expo prebuild` / `expo run:ios`) → "development"
//
// EAS Build reliably injects EAS_BUILD_PROFILE (the active --profile name)
// into the environment for the whole build, including config evaluation /
// prebuild. It is NOT set during a local `expo prebuild`, so an unset
// value falls through to "development" — keeping local simulator/device
// dev builds working. Only the two profiles that are genuinely
// production-signed opt into "production".
//
// See CLAUDE.md "Notes / gotchas" and PROGRESS_LOG 2026-05-31.
module.exports = ({ config }) => {
  const profile = process.env.EAS_BUILD_PROFILE;
  const apsEnvironment =
    profile === 'production' || profile === 'preview' ? 'production' : 'development';

  return {
    ...config,
    ios: {
      ...config.ios,
      entitlements: {
        ...config.ios?.entitlements,
        'aps-environment': apsEnvironment,
      },
    },
  };
};
