import React from 'react';
import { SafeAreaView, ScrollView, View, Text, Pressable, StyleSheet } from 'react-native';
import { useRouter } from 'expo-router';
import { colors, spacing, typography } from '@/constants/theme';

// First-pass terms of service. Same posture as the privacy policy:
// plain language, honest, not lawyer-drafted. Acceptable use clauses
// are intentionally specific (re-mixing real people's likenesses) so
// they're enforceable rather than vague. Replace contact email + any
// jurisdiction notes before submitting to App Store / Play Store.

const LAST_UPDATED = 'April 2026';

export default function TermsScreen() {
  const router = useRouter();
  return (
    <SafeAreaView style={styles.safe}>
      <View style={styles.header}>
        <Pressable onPress={() => router.back()} style={styles.back}>
          <Text style={styles.backText}>←</Text>
        </Pressable>
        <View style={styles.headerTitle}>
          <Text style={styles.headerLabel}>Account</Text>
          <Text style={styles.title}>Terms of Service</Text>
        </View>
        <View style={{ width: 40 }} />
      </View>
      <ScrollView contentContainerStyle={styles.content}>
        <Text style={styles.meta}>Last updated: {LAST_UPDATED}</Text>

        <Section title="What this app does">
          <P>
            What If lets you upload photos and generate AI-transformed versions
            (different ethnicity, age, gender presentation, celebrity likeness
            mashups, etc.). Outputs are produced by Google's Gemini image model
            and are AI-generated depictions, not real photographs.
          </P>
        </Section>

        <Section title="Acceptable use">
          <P>
            By using What If, you agree NOT to:
          </P>
          <P>
            <B>•</B> Upload photos of anyone — including yourself — without that
            person's consent.
          </P>
          <P>
            <B>•</B> Generate or share images intended to harass, defame, deceive,
            or sexualize any real person.
          </P>
          <P>
            <B>•</B> Use the celebrity, political, or ethnicity-blend categories
            on photos that include minors. The app blocks this in software, and
            attempting to bypass that block violates these terms.
          </P>
          <P>
            <B>•</B> Use the app to impersonate, defraud, or mislead — including
            posting outputs without making clear that they're AI-generated.
          </P>
          <P>
            <B>•</B> Use the app to generate sexual content, content involving
            minors, or content depicting graphic violence.
          </P>
          <P>
            <B>•</B> Reverse-engineer the prompts, scrape the API, or otherwise
            abuse the service.
          </P>
        </Section>

        <Section title="The outputs are AI-generated">
          <P>
            Every image What If produces is a synthetic depiction generated by an
            AI model. It is not a photograph of the depicted person doing the
            depicted thing. If you share an output anywhere — social media,
            messaging, print — you are responsible for making clear it is
            AI-generated. Many platforms now require this disclosure; check the
            policies of wherever you're posting.
          </P>
        </Section>

        <Section title="Your content">
          <P>
            <B>You keep your rights.</B> You retain whatever rights you had to the
            photos you upload. We don't claim ownership of your originals or the
            generated outputs.
          </P>
          <P>
            <B>License to operate.</B> To run the service we need a narrow license
            from you: permission to process your uploaded photo through the
            Gemini API, to store it in our backend, and to display the generated
            outputs back to you. This license is solely for operating the app and
            ends when you delete your account.
          </P>
          <P>
            <B>Consent for premium categories.</B> The premium categories
            (celebrity, political, ethnicity blends) re-mix recognizable real
            people. By using them, you confirm you have the consent of everyone
            depicted in your uploaded photo.
          </P>
        </Section>

        <Section title="Subscriptions">
          <P>
            Pro is a paid subscription that unlocks unlimited generations and the
            premium categories. Subscriptions are managed by Apple (App Store) or
            Google (Play Store) and renew automatically until cancelled in those
            stores. We don't process payments directly.
          </P>
          <P>
            Refund requests for App Store / Play Store purchases must go through
            Apple or Google respectively — we don't have the ability to issue
            refunds on those platforms.
          </P>
        </Section>

        <Section title="No warranty">
          <P>
            What If is provided "as is." The AI model occasionally produces
            distorted, low-quality, or unexpected outputs — that's the nature of
            generative image models. We make no guarantee about the quality,
            accuracy, or appropriateness of any output.
          </P>
        </Section>

        <Section title="Liability">
          <P>
            To the extent permitted by law, we are not liable for indirect,
            incidental, or consequential damages arising from your use of the
            app. Our total liability is limited to the amount you paid us (if
            any) in the twelve months prior to the event giving rise to the
            claim.
          </P>
        </Section>

        <Section title="Termination">
          <P>
            You can stop using the app at any time and delete your account from
            Profile → Delete Account.
          </P>
          <P>
            We may suspend or terminate your access if you violate these terms,
            particularly the Acceptable Use clauses above. We aim to act
            proportionally — a single misstep won't typically trigger a ban — but
            we reserve the right.
          </P>
        </Section>

        <Section title="Changes">
          <P>
            We may update these terms. The "Last updated" date at the top
            changes when we do. For substantive changes we'll surface a notice
            in the app.
          </P>
        </Section>

        <Section title="Contact">
          <P>
            Questions: <B>support@whatif.app</B> (replace with your real address
            before launch).
          </P>
        </Section>
      </ScrollView>
    </SafeAreaView>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <View style={styles.section}>
      <Text style={styles.sectionTitle}>{title}</Text>
      {children}
    </View>
  );
}

function P({ children }: { children: React.ReactNode }) {
  return <Text style={styles.paragraph}>{children}</Text>;
}

function B({ children }: { children: React.ReactNode }) {
  return <Text style={styles.bold}>{children}</Text>;
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.bg },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  back: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center' },
  backText: { color: colors.textPrimary, fontSize: 26 },
  headerTitle: { alignItems: 'center', flex: 1 },
  headerLabel: { ...typography.label, color: colors.textLabel, fontSize: 10, marginBottom: 2 },
  title: { ...typography.h3, color: colors.textPrimary },
  content: { padding: spacing.xl, gap: spacing.lg, paddingBottom: spacing.xxxl },
  meta: { ...typography.caption, color: colors.textMuted, marginBottom: spacing.sm },
  section: { gap: spacing.sm },
  sectionTitle: { ...typography.h3, color: colors.textPrimary, marginTop: spacing.md },
  paragraph: { ...typography.body, color: colors.textSecondary, lineHeight: 22 },
  bold: { color: colors.textPrimary, fontWeight: '700' },
});
